name: models
description: Dart package which manages the shared models.
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  equatable: ^2.0.0
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.11.2
