name: user_repository
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  equatable: ^2.0.0
  firebase_auth: ^6.1.2
  uuid: ^3.0.0
  shared_preferences: ^2.5.3
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  logger: ^2.6.0
  models:
    path: ../models

dev_dependencies:
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.11.2
