name: chat_repository
description: Dart package which manages the chat domain.
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  equatable: ^2.0.0
  cloud_firestore: ^6.1.0
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  firebase_database: ^12.1.0
  rxdart: ^0.28.0
  models:
    path: ../models
  api_client:
    path: ../api_client

dev_dependencies:
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.11.2
